x-environment: &default-environment
  TZ: Asia/Taipei
  MARIADB_DATABASE: example
  MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db-password

networks:
  default:
  docker-proxy:
  db-net:

volumes:
  db-data:

secrets:
  db-password:
    file: db/db-password
  user-password:
    file: db/user-password

services:
  db:
    image: mariadb:lts
    restart: always
    environment:
      <<: *default-environment
    networks:
      - db-net
    secrets:
      - db-password
      - user-password
    volumes:
      - db-data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 2m
      start_interval: 10s
      interval: 3s
      timeout: 5s
      retries: 3

  crawler:
    build:
      context: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      <<: *default-environment
      PYTHONUNBUFFERED: 1
      MARIADB_HOST: db
    networks:
      - db-net
    secrets:
      - db-password
    volumes:
      - ./data:/data
  backup:
    build:
      context: services/backup
    restart: always
    depends_on:
      db:
        condition: service_healthy
    stop_grace_period: 30s
    environment:
      <<: *default-environment
      MAX_BACKUPS: 30
    networks:
      - db-net
    secrets:
      - db-password
    volumes:
      - ./data:/app/data

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    environment:
      CONTAINERS: 1
    networks:
      - docker-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: wget --spider http://localhost:2375/version || exit 1
      start_period: 2m
      start_interval: 10s
      interval: 3s
      timeout: 5s
      retries: 3
    privileged: true

  traefik:
    build:
      context: services/traefik
    depends_on:
      docker-socket-proxy:
        condition: service_healthy
    networks:
      - default
      - docker-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/traefik/letsencrypt:/letsencrypt

