volumes:
    db-data:

secrets:
    db-password:
        file: db/db-password
    user-password:
        file: db/user-password

networks:
    backnet:

services:
    db:
        image: mariadb:lts
        restart: always
        environment:
            - TZ=Asia/Taipei
            - MARIADB_DATABASE=example
            - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db-password
        secrets:
            - db-password
            - user-password
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - backnet
        expose:
            - 3306
            - 33060
        healthcheck:
            test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
            start_period: 1m
            start_interval: 10s
            interval: 3s
            timeout: 5s
            retries: 3

    app:
        build:
            context: .
        restart : always
        depends_on:
            db:
                condition: service_healthy
        environment:
            - TZ=Asia/Taipei
            - PYTHONUNBUFFERED=1
        secrets:
            - db-password
        volumes:
            - ./data:/data
        networks:
            - backnet
        healthcheck:
            test: ["CMD", "test", "-f", "/home/eva/ready"]
            start_period: 5m
            start_interval: 10s
            interval: 3s
            timeout: 10s
            retries: 3

    backup:
        build:
          context: backup
        restart : always
        depends_on:
            db:
                condition: service_healthy
            app:
                condition: service_healthy
        stop_grace_period: 30s
        environment:
            - TZ=Asia/Taipei
        secrets:
            - db-password
        volumes:
            - ./data:/data
        networks:
            - backnet

