volumes:
    db-data:

secrets:
    db-password:
        file: db/password.txt
    user-password:
        file: db/user-password.txt

networks:
    backnet:

services:
    db:
        image: mariadb:lts
        restart: always
        healthcheck:
            test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
            start_period: 1m
            start_interval: 10s
            interval: 3s
            timeout: 5s
            retries: 3
        secrets:
            - db-password
            - user-password
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - backnet
        expose:
            - 3306
            - 33060
        environment:
            - TZ=Asia/Taipei
            - MARIADB_DATABASE=example
            - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db-password
            # - MYSQL_USER=eva
            # - MYSQL_PASSWORD_FILE=/run/secrets/user-password

    app:
        build:
            context: .
        depends_on:
            db:
                condition: service_healthy
        environment:
            - TZ=Asia/Taipei
            - PYTHONUNBUFFERED=1
        secrets:
            - db-password
        volumes:
            - ./data:/data
        networks:
            - backnet

    backup:
        build:
          context: backup
        depends_on:
            db:
                condition: service_healthy
        environment:
            - TZ=Asia/Taipei
        secrets:
            - db-password
        volumes:
            - ./data:/data
        networks:
            - backnet

